name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{env.DOTNET_ROOT}}/currencyConverter/appsettings.json'
      env:
        ConnectionStrings.freeCurrencyApi: ${{ secrets.FREE_CURRENCY_API_TOKEN }}
    - name: Build the Docker image
      run: |
        cd src
        pwd
        ls -al
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
